apiVersion: v1
kind: Service
metadata:
  name: business-rule-engine
  labels:
    app: business-rule-engine
spec:
    type: ClusterIP
    selector:
        app: business-rule-engine
    ports:
     - protocol: TCP
       port: 8080
       targetPort: 8080